spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: on
  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

mybatis:
  configuration:
    map-underscore-to-camel-case: on